import "dotenv/config";
import { PrismaClient } from "@/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const specialists = [
  // ── Clinical Psychologists ──────────────────────────────────
  {
    name: "Dr. Amara Okonkwo",
    title: "Clinical Psychologist",
    specialization: "Clinical Psychology",
    bio: "Dr. Amara Okonkwo brings over 15 years of experience in evidence-based psychotherapy for anxiety, depression, and emotional dysregulation. She trained at the University of Lagos and completed her doctorate at UCL London. She is known for her culturally sensitive, person-centred approach.",
    yearsOfExperience: 15,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba", "Igbo"],
    email: "amara.okonkwo@mindbridge.app",
    imageUrl: "/specialists/amara-okonkwo.jpg",
    rating: 4.9,
    availability: "Mon-Thu, 9am-5pm",
    consultationType: "both",
    tags: ["anxiety", "depression", "CBT", "trauma", "emotional regulation"],
    verified: true,
  },
  {
    name: "Dr. Chukwuemeka Eze",
    title: "Clinical Psychologist",
    specialization: "Clinical Psychology",
    bio: "Dr. Eze specialises in cognitive-behavioural therapy and mindfulness-based interventions for adults dealing with chronic stress and burnout. With 12 years in private practice, he has helped hundreds of professionals reclaim their mental wellbeing.",
    yearsOfExperience: 12,
    location: "Abuja, Nigeria",
    languages: ["English", "Igbo", "Hausa"],
    imageUrl: "/specialists/chukwuemeka-eze.jpg",
    rating: 4.8,
    availability: "Tue-Sat, 10am-6pm",
    consultationType: "virtual",
    tags: ["stress", "burnout", "CBT", "mindfulness", "professionals"],
    verified: true,
  },
  {
    name: "Dr. Folake Adeyemi",
    title: "Clinical Psychologist",
    specialization: "Clinical Psychology",
    bio: "Dr. Folake Adeyemi is a compassionate psychologist specialising in childhood trauma and its adult manifestations. She holds a PhD from the University of Ibadan and has published research on intergenerational trauma in West African contexts.",
    yearsOfExperience: 10,
    location: "Ibadan, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/folake-adeyemi.jpg",
    rating: 4.7,
    availability: "Mon-Fri, 8am-4pm",
    consultationType: "both",
    tags: ["trauma", "childhood trauma", "PTSD", "attachment", "depression"],
    verified: true,
  },

  // ── CBT Therapists ──────────────────────────────────────────
  {
    name: "Ngozi Chibuike",
    title: "CBT Therapist",
    specialization: "Cognitive Behavioural Therapy",
    bio: "Ngozi is a certified CBT therapist with a master's degree from the University of Benin. She works primarily with young adults navigating anxiety, perfectionism, and academic pressure, using structured yet warm therapeutic techniques.",
    yearsOfExperience: 7,
    location: "Benin City, Nigeria",
    languages: ["English", "Edo"],
    imageUrl: "/specialists/ngozi-chibuike.jpg",
    rating: 4.8,
    availability: "Mon-Sat, 9am-5pm",
    consultationType: "virtual",
    tags: ["anxiety", "CBT", "perfectionism", "academic stress", "young adults"],
    verified: true,
  },
  {
    name: "Emeka Nwosu",
    title: "CBT Therapist",
    specialization: "Cognitive Behavioural Therapy",
    bio: "Emeka Nwosu combines CBT with acceptance and commitment therapy (ACT) to help clients break unhelpful thought cycles. He has worked with athletes, students, and corporate professionals over his 9-year career.",
    yearsOfExperience: 9,
    location: "Port Harcourt, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/emeka-nwosu.jpg",
    rating: 4.6,
    availability: "Tue-Fri, 11am-7pm",
    consultationType: "both",
    tags: ["anxiety", "CBT", "ACT", "depression", "performance anxiety"],
    verified: true,
  },

  // ── Trauma Therapists ───────────────────────────────────────
  {
    name: "Dr. Hauwa Musa",
    title: "Trauma-Informed Therapist",
    specialization: "Trauma Therapy",
    bio: "Dr. Hauwa Musa is a licensed trauma specialist trained in EMDR (Eye Movement Desensitization and Reprocessing). She has worked extensively with survivors of domestic violence and conflict-related trauma across Northern Nigeria.",
    yearsOfExperience: 14,
    location: "Kano, Nigeria",
    languages: ["English", "Hausa", "Fulani"],
    imageUrl: "/specialists/hauwa-musa.jpg",
    rating: 4.9,
    availability: "Mon-Thu, 9am-4pm",
    consultationType: "both",
    tags: ["trauma", "EMDR", "PTSD", "domestic violence", "grief"],
    verified: true,
  },
  {
    name: "Adaeze Obi",
    title: "Trauma Specialist",
    specialization: "Trauma Therapy",
    bio: "Adaeze Obi works with individuals who have experienced relational trauma, helping them rebuild trust and emotional safety. Her somatic-informed approach integrates body-based techniques with narrative therapy.",
    yearsOfExperience: 6,
    location: "Enugu, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/adaeze-obi.jpg",
    rating: 4.7,
    availability: "Wed-Sun, 10am-6pm",
    consultationType: "virtual",
    tags: ["trauma", "somatic therapy", "relational trauma", "grief", "PTSD"],
    verified: false,
  },

  // ── Psychiatrists ───────────────────────────────────────────
  {
    name: "Dr. Babatunde Fashola",
    title: "Consultant Psychiatrist",
    specialization: "Psychiatry",
    bio: "Dr. Babatunde Fashola is a consultant psychiatrist with specialisations in mood disorders, psychosis, and dual diagnosis. He trained at Lagos University Teaching Hospital and has 18 years of clinical experience.",
    yearsOfExperience: 18,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    email: "b.fashola@mindbridge.app",
    imageUrl: "/specialists/babatunde-fashola.jpg",
    rating: 4.9,
    availability: "Mon-Fri, 9am-3pm",
    consultationType: "both",
    tags: ["psychiatry", "depression", "bipolar", "psychosis", "medication management"],
    verified: true,
  },
  {
    name: "Dr. Zainab Garba",
    title: "Psychiatrist",
    specialization: "Psychiatry",
    bio: "Dr. Zainab Garba focuses on women's mental health, including perinatal psychiatry and trauma in women. She is one of the few psychiatrists in the North specialising in postpartum depression and anxiety.",
    yearsOfExperience: 11,
    location: "Kaduna, Nigeria",
    languages: ["English", "Hausa", "Arabic"],
    imageUrl: "/specialists/zainab-garba.jpg",
    rating: 4.8,
    availability: "Mon, Wed, Fri, 10am-4pm",
    consultationType: "virtual",
    tags: ["psychiatry", "women's mental health", "postpartum", "anxiety", "depression"],
    verified: true,
  },

  // ── Counsellors / Therapists ────────────────────────────────
  {
    name: "Yewande Bello",
    title: "Licensed Counsellor",
    specialization: "Counselling",
    bio: "Yewande Bello is a warm and approachable counsellor who helps individuals navigate life transitions, relationship difficulties, and low mood. She has a particular interest in supporting students and young professionals.",
    yearsOfExperience: 5,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/yewande-bello.jpg",
    rating: 4.6,
    availability: "Mon-Sat, 8am-6pm",
    consultationType: "virtual",
    tags: ["depression", "life transitions", "grief", "relationships", "students"],
    verified: true,
  },
  {
    name: "Sunday Danladi",
    title: "Licensed Therapist",
    specialization: "Counselling",
    bio: "Sunday Danladi is a therapist grounded in person-centred and integrative approaches. He works with men who struggle to articulate their emotional experiences, helping them build self-awareness and healthy communication.",
    yearsOfExperience: 8,
    location: "Jos, Nigeria",
    languages: ["English", "Hausa", "Berom"],
    imageUrl: "/specialists/sunday-danladi.jpg",
    rating: 4.5,
    availability: "Tue-Sat, 9am-5pm",
    consultationType: "both",
    tags: ["stress", "men's mental health", "emotional intelligence", "relationships"],
    verified: false,
  },

  // ── Family / Marriage Therapists ────────────────────────────
  {
    name: "Mrs. Chidinma Okafor",
    title: "Family Therapist",
    specialization: "Family Therapy",
    bio: "Chidinma Okafor is a systemic family therapist helping families improve communication, resolve conflict, and heal relational wounds. She brings 11 years of experience working with blended families and multigenerational dynamics.",
    yearsOfExperience: 11,
    location: "Onitsha, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/chidinma-okafor.jpg",
    rating: 4.8,
    availability: "Mon-Thu, 10am-5pm",
    consultationType: "both",
    tags: ["family therapy", "parenting", "conflict resolution", "relationships"],
    verified: true,
  },
  {
    name: "Mr. Rasheed Adekunle",
    title: "Marriage & Couples Counsellor",
    specialization: "Marriage Counselling",
    bio: "Rasheed Adekunle uses Emotionally Focused Therapy (EFT) to help couples rebuild intimacy and trust. He has worked with over 300 couples in 13 years of practice and holds certifications from the International Centre for Excellence in EFT.",
    yearsOfExperience: 13,
    location: "Abuja, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/rasheed-adekunle.jpg",
    rating: 4.9,
    availability: "Mon-Fri, 4pm-8pm, Sat 10am-2pm",
    consultationType: "both",
    tags: ["marriage", "couples therapy", "EFT", "intimacy", "infidelity recovery"],
    verified: true,
  },

  // ── Child Psychologists ─────────────────────────────────────
  {
    name: "Dr. Temi Adesanya",
    title: "Child & Adolescent Psychologist",
    specialization: "Child Psychology",
    bio: "Dr. Temi Adesanya specialises in emotional and behavioural challenges in children and teenagers. She uses play therapy, CBT for youth, and parent coaching to create lasting positive change.",
    yearsOfExperience: 9,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/temi-adesanya.jpg",
    rating: 4.9,
    availability: "Mon-Fri, 9am-4pm",
    consultationType: "both",
    tags: ["child psychology", "adolescent", "ADHD", "anxiety", "play therapy"],
    verified: true,
  },
  {
    name: "Mrs. Obiageli Nwofor",
    title: "Child Psychologist",
    specialization: "Child Psychology",
    bio: "Obiageli Nwofor works with children aged 3-16 experiencing anxiety, social difficulties, and learning challenges. She offers school consultations and works closely with parents to ensure consistency between home and therapy.",
    yearsOfExperience: 6,
    location: "Owerri, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/obiageli-nwofor.jpg",
    rating: 4.7,
    availability: "Mon-Sat, 9am-3pm",
    consultationType: "both",
    tags: ["child psychology", "learning difficulties", "anxiety", "social skills", "parenting"],
    verified: false,
  },

  // ── Behavioural Therapists ──────────────────────────────────
  {
    name: "Dr. Musa Ibrahim",
    title: "Behavioural Therapist",
    specialization: "Behavioural Therapy",
    bio: "Dr. Musa Ibrahim applies behavioural and DBT techniques to help clients with sleep disorders, compulsive behaviours, and emotional dysregulation. He has published in several African psychology journals.",
    yearsOfExperience: 12,
    location: "Maiduguri, Nigeria",
    languages: ["English", "Hausa", "Kanuri"],
    imageUrl: "/specialists/musa-ibrahim.jpg",
    rating: 4.6,
    availability: "Mon-Thu, 9am-5pm",
    consultationType: "virtual",
    tags: ["sleep issues", "DBT", "behavioural therapy", "OCD", "emotional regulation"],
    verified: true,
  },
  {
    name: "Grace Okonkwo",
    title: "Behavioural Therapist",
    specialization: "Behavioural Therapy",
    bio: "Grace Okonkwo helps clients build healthier habits and break destructive patterns using applied behaviour analysis and habit reversal training. She specialises in sleep hygiene and digital addiction.",
    yearsOfExperience: 4,
    location: "Uyo, Nigeria",
    languages: ["English", "Efik", "Ibibio"],
    imageUrl: "/specialists/grace-okonkwo.jpg",
    rating: 4.5,
    availability: "Tue-Sat, 10am-6pm",
    consultationType: "virtual",
    tags: ["sleep issues", "habits", "behavioural therapy", "digital wellness"],
    verified: false,
  },

  // ── Addiction Counsellors ───────────────────────────────────
  {
    name: "Mr. Ifeanyi Okeke",
    title: "Addiction Counsellor",
    specialization: "Addiction Counselling",
    bio: "Ifeanyi Okeke has 16 years of experience supporting individuals in recovery from substance dependence, behavioural addictions, and co-occurring mental health conditions. He integrates motivational interviewing with 12-step facilitation.",
    yearsOfExperience: 16,
    location: "Lagos, Nigeria",
    languages: ["English", "Igbo", "Pidgin"],
    imageUrl: "/specialists/ifeanyi-okeke.jpg",
    rating: 4.8,
    availability: "Mon-Fri, 8am-5pm",
    consultationType: "both",
    tags: ["addiction", "substance use", "recovery", "co-occurring disorders"],
    verified: true,
  },
  {
    name: "Mrs. Blessing Uche",
    title: "Addiction Therapist",
    specialization: "Addiction Counselling",
    bio: "Blessing Uche works with individuals and families affected by addiction, using community reinforcement and harm reduction approaches. She also facilitates group therapy sessions for those in recovery.",
    yearsOfExperience: 7,
    location: "Calabar, Nigeria",
    languages: ["English", "Efik"],
    imageUrl: "/specialists/blessing-uche.jpg",
    rating: 4.6,
    availability: "Mon, Wed, Fri-Sat, 10am-5pm",
    consultationType: "both",
    tags: ["addiction", "harm reduction", "group therapy", "family support"],
    verified: false,
  },

  // ── Anxiety Specialists ─────────────────────────────────────
  {
    name: "Dr. Adeola Savage",
    title: "Anxiety Specialist",
    specialization: "Anxiety Disorders",
    bio: "Dr. Adeola Savage is one of Lagos's leading anxiety specialists, trained in exposure and response prevention (ERP) and acceptance-based therapies. She helps clients regain control over panic disorder, social anxiety, and generalised anxiety.",
    yearsOfExperience: 13,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    email: "adeola.savage@mindbridge.app",
    imageUrl: "/specialists/adeola-savage.jpg",
    rating: 4.9,
    availability: "Mon-Fri, 9am-5pm",
    consultationType: "both",
    tags: ["anxiety", "panic disorder", "social anxiety", "OCD", "ERP", "GAD"],
    verified: true,
  },
  {
    name: "Kemi Fadahunsi",
    title: "Anxiety & Stress Therapist",
    specialization: "Anxiety Disorders",
    bio: "Kemi Fadahunsi combines mindfulness-based stress reduction with CBT techniques to help clients manage anxiety and chronic worry. She offers flexible evening and weekend appointments for working professionals.",
    yearsOfExperience: 5,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/kemi-fadahunsi.jpg",
    rating: 4.7,
    availability: "Weekdays 5pm-9pm, Sat 9am-3pm",
    consultationType: "virtual",
    tags: ["anxiety", "stress", "MBSR", "mindfulness", "worry", "professionals"],
    verified: true,
  },

  // ── Depression Specialists ──────────────────────────────────
  {
    name: "Dr. Tunde Oyelaran",
    title: "Depression Specialist",
    specialization: "Mood Disorders",
    bio: "Dr. Tunde Oyelaran has spent two decades treating depression across its many presentations — from mild low mood to treatment-resistant depression. He uses an integrative model combining pharmacotherapy referrals with psychotherapy.",
    yearsOfExperience: 20,
    location: "Ibadan, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/tunde-oyelaran.jpg",
    rating: 4.9,
    availability: "Mon-Fri, 10am-4pm",
    consultationType: "both",
    tags: ["depression", "mood disorders", "bipolar", "grief", "integration"],
    verified: true,
  },
  {
    name: "Dr. Sandra Nkem",
    title: "Psychologist & Depression Therapist",
    specialization: "Mood Disorders",
    bio: "Dr. Sandra Nkem specialises in treating depression, particularly in women, students, and those navigating grief and loss. She uses behavioural activation, interpersonal therapy, and narrative approaches.",
    yearsOfExperience: 8,
    location: "Abuja, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/sandra-nkem.jpg",
    rating: 4.7,
    availability: "Mon-Sat, 9am-5pm",
    consultationType: "virtual",
    tags: ["depression", "grief", "women's health", "interpersonal therapy", "students"],
    verified: true,
  },

  // ── Stress Management Coaches ───────────────────────────────
  {
    name: "Lanre Akintola",
    title: "Stress Management Coach",
    specialization: "Stress Management",
    bio: "Lanre Akintola is a certified coach and wellness consultant who helps executives and teams build resilience and reduce burnout. His methodology blends neuroscience, productivity frameworks, and mindfulness.",
    yearsOfExperience: 8,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/lanre-akintola.jpg",
    rating: 4.7,
    availability: "Mon-Fri, 7am-9am, 6pm-9pm",
    consultationType: "virtual",
    tags: ["stress", "burnout", "productivity", "resilience", "executive coaching"],
    verified: true,
  },
  {
    name: "Mrs. Fatima Aliyu",
    title: "Wellness & Stress Coach",
    specialization: "Stress Management",
    bio: "Fatima Aliyu draws on holistic wellness practices and cognitive coaching to help individuals manage work-life stress, improve sleep, and cultivate sustainable mental health routines.",
    yearsOfExperience: 6,
    location: "Abuja, Nigeria",
    languages: ["English", "Hausa", "French"],
    imageUrl: "/specialists/fatima-aliyu.jpg",
    rating: 4.6,
    availability: "Mon-Sat, 9am-6pm",
    consultationType: "both",
    tags: ["stress", "sleep issues", "wellness", "mindfulness", "work-life balance"],
    verified: false,
  },

  // ── Mindfulness & Wellbeing ─────────────────────────────────
  {
    name: "Sola Ajayi",
    title: "Mindfulness-Based Therapist",
    specialization: "Mindfulness & Wellbeing",
    bio: "Sola Ajayi is a trained mindfulness teacher and therapist who integrates MBCT and compassion-focused therapy into her work. She runs individual sessions and group mindfulness programmes online.",
    yearsOfExperience: 7,
    location: "Remote / Nationwide",
    languages: ["English", "Yoruba"],
    imageUrl: "/specialists/sola-ajayi.jpg",
    rating: 4.8,
    availability: "Flexible — book anytime",
    consultationType: "virtual",
    tags: ["mindfulness", "MBCT", "stress", "anxiety", "self-compassion", "wellbeing"],
    verified: true,
  },
  {
    name: "David Abah",
    title: "Positive Psychology Coach",
    specialization: "Mindfulness & Wellbeing",
    bio: "David Abah works with clients to build psychological strengths, cultivate meaning, and improve overall wellbeing. He draws on positive psychology, goal-setting, and strengths-based coaching.",
    yearsOfExperience: 4,
    location: "Port Harcourt, Nigeria",
    languages: ["English", "Ijaw"],
    imageUrl: "/specialists/david-abah.jpg",
    rating: 4.5,
    availability: "Mon-Fri, 8am-8pm",
    consultationType: "virtual",
    tags: ["wellbeing", "positive psychology", "coaching", "motivation", "resilience"],
    verified: false,
  },

  // ── Specialist for Sleep ────────────────────────────────────
  {
    name: "Dr. Aisha Mohammed",
    title: "Sleep & Behavioural Therapist",
    specialization: "Sleep Health",
    bio: "Dr. Aisha Mohammed specialises in cognitive behavioural therapy for insomnia (CBT-I) and other sleep disorders. She has worked with shift workers, new parents, and individuals with anxiety-driven sleep problems.",
    yearsOfExperience: 10,
    location: "Abuja, Nigeria",
    languages: ["English", "Hausa", "Arabic"],
    imageUrl: "/specialists/aisha-mohammed.jpg",
    rating: 4.8,
    availability: "Mon-Fri, 9am-5pm",
    consultationType: "both",
    tags: ["sleep issues", "CBT-I", "insomnia", "anxiety", "sleep hygiene"],
    verified: true,
  },

  // ── Additional Diverse Specialists ─────────────────────────
  {
    name: "Dr. Emeka Obi-Okafor",
    title: "Neuropsychologist",
    specialization: "Neuropsychology",
    bio: "Dr. Emeka Obi-Okafor brings neuropsychological expertise to the assessment and treatment of attention, memory, and executive function difficulties. He works with adults who suspect or have diagnosed ADHD.",
    yearsOfExperience: 9,
    location: "Lagos, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/emeka-obi-okafor.jpg",
    rating: 4.7,
    availability: "Mon-Fri, 10am-4pm",
    consultationType: "both",
    tags: ["ADHD", "neuropsychology", "cognitive assessment", "executive function"],
    verified: true,
  },
  {
    name: "Nneka Obaseki",
    title: "Psychotherapist",
    specialization: "Psychotherapy",
    bio: "Nneka Obaseki is an integrative psychotherapist working with individuals experiencing existential challenges, identity questions, and life-purpose issues. She draws on humanistic and existential frameworks.",
    yearsOfExperience: 11,
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba", "Bini"],
    imageUrl: "/specialists/nneka-obaseki.jpg",
    rating: 4.8,
    availability: "Tue-Sat, 10am-6pm",
    consultationType: "both",
    tags: ["existential therapy", "identity", "life transitions", "self-esteem", "purpose"],
    verified: true,
  },
  {
    name: "Mr. Ikechukwu Eze",
    title: "Grief & Loss Counsellor",
    specialization: "Grief Counselling",
    bio: "Ikechukwu Eze provides compassionate support to individuals navigating bereavement, pregnancy loss, and the grief of life changes. He uses narrative therapy and continuing bonds theory in his practice.",
    yearsOfExperience: 7,
    location: "Enugu, Nigeria",
    languages: ["English", "Igbo"],
    imageUrl: "/specialists/ikechukwu-eze.jpg",
    rating: 4.6,
    availability: "Mon-Fri, 9am-5pm, Sat 10am-1pm",
    consultationType: "both",
    tags: ["grief", "bereavement", "loss", "trauma", "pregnancy loss"],
    verified: false,
  },
];

async function main() {
  console.log("🌱 Seeding specialists...");

  for (const specialist of specialists) {
    await prisma.specialist.upsert({
      where: {
        // Use a stable composite: name + title
        // We create a unique constraint-free upsert via findFirst + create
        id: `seed-${specialist.name.toLowerCase().replace(/\s+/g, "-")}`,
      },
      update: {
        ...specialist,
      },
      create: {
        id: `seed-${specialist.name.toLowerCase().replace(/\s+/g, "-")}`,
        ...specialist,
      },
    });
    console.log(`  ✅ ${specialist.name} — ${specialist.title}`);
  }

  console.log(`\n✨ Seeded ${specialists.length} specialists successfully.`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
